import {Note} from "./Note";

/**
 * A [[Beam]] - the bar grouping multiple consecutive [[Note]]s.
 */
export class Beam {

    private notes: Note[] = [];
    private extendedNoteList: Note[] = [];
    public BeamNumber: number;
    public BeamNumberOffsetToXML: number = 0;
    public AutoGenerated: boolean = false;
    /** Note indices where secondary beams (16th and shorter) should break. */
    public SecondaryBreakIndices: number[] = [];

    /**
     * Whether every authored stem endpoint in this beam describes the same
     * horizontal beam line. VexFlow still chooses the responsive vertical offset.
     */
    public get HasFlatBeamHint(): boolean {
        if (this.AutoGenerated || this.notes.length < 2) {
            return false;
        }
        const endpoints: Array<number | undefined> = this.notes.map(
            (note: Note): number | undefined => note.StemDefaultYXml,
        );
        if (endpoints.some((endpoint: number | undefined): boolean =>
            endpoint === undefined || !Number.isFinite(endpoint))) {
            return false;
        }
        const finiteEndpoints: number[] = endpoints as number[];
        return Math.max(...finiteEndpoints) - Math.min(...finiteEndpoints) <= 0.5;
    }

    constructor(beamNumber: number = 1, beamNumberOffsetToXML: number = 0) {
        this.BeamNumber = beamNumber;
        this.BeamNumberOffsetToXML = beamNumberOffsetToXML;
    }

    public get Notes(): Note[] {
        return this.notes;
    }
    public set Notes(value: Note[]) {
        this.notes = value;
    }
    public get ExtendedNoteList(): Note[] {
        return this.extendedNoteList;
    }
    public set ExtendedNoteList(value: Note[]) {
        this.extendedNoteList = value;
    }

    /**
     * Perform all the appropriate actions for adding a singleNote to the Beam.
     * @param note
     */
    public addNoteToBeam(note: Note): void {
        if (note) {
            note.NoteBeam = this;
            this.notes.push(note);
            this.extendedNoteList.push(note);
        }
    }

}

export enum BeamEnum {
    BeamNone = -1,
    BeamBegin = 0,
    BeamContinue = 1,
    BeamEnd = 2,
    BeamForward = 3,
    BeamBackward = 4,
}
